# -*- encoding: utf-8 -*-
from __future__ import unicode_literals

from ..brands import Lada, Nissan, Opel, Renault


WMI = {
    '1B': 'Dodge',
    '1C': 'Chrysler',
    '1D': 'Dodge',
    '1F': 'Ford',
    '1F9': 'FWD Corp.',
    '1FU': 'Freightliner',
    '1FV': 'Freightliner',
    '1G': 'General Motors',
    '1G1': 'Chevrolet',
    '1G2': 'Pontiac',
    '1G3': 'Oldsmobile',
    '1G4': 'Buick',
    '1G6': 'Cadillac',
    '1G8': 'Saturn',
    '1G9': 'Google',
    '1GB': 'Chevrolet USA',
    '1GC': 'Chevrolet',
    '1GM': 'Pontiac',
    '1GN': 'Chevrolet USA',
    '1GT': 'GMC Truck',
    '1GY': 'Cadillac',
    '1H': 'Honda',
    '1HD': 'Harley-Davidson',
    '1J': 'Jeep',
    '1L': 'Lincoln',
    '1M': 'Mercury',
    '1M1': 'Mack Truck',
    '1M2': 'Mack Truck',
    '1M3': 'Mack Truck',
    '1M4': 'Mack Truck',
    '1M9': 'Mynatt Truck & Equipment',
    '1ME': 'Mercury',
    '1N': Nissan(),
    '1NX': 'NUMMI',
    '1P3': 'Plymouth',
    '1R9': 'Roadrunner Hay Squeeze',
    '1V1': 'Volkswagen USA (Commercials)',
    '1VW': 'Volkswagen',
    '1XK': 'Kenworth',
    '1XP': 'Peterbilt',
    '1YV': 'Mazda',
    '1ZV': 'Auto Alliance International',
    '2A4': 'Chrysler Canada',
    '2B3': 'Dodge Canada',
    '2C3': 'Chrysler',
    '2C4': 'Chrysler Canada',
    '2CN': 'CAMI',
    '2D3': 'Dodge',
    '2D4': 'Dodge Canada',
    '2DG': 'Ontario Drive & Gear',
    '2F': 'Ford',
    '2FT': 'Ford Motor Company',
    '2FU': 'Freightliner',
    '2FV': 'Freightliner',
    '2FZ': 'Sterling',
    '2G': 'General Motors',
    '2G1': 'Chevrolet',
    '2G2': 'Pontiac',
    '2G3': 'Oldsmobile',
    '2G4': 'Buick',
    '2G6': 'Cadillac',
    '2G9': 'Gnome Homes',
    '2GC': 'Chevrolet Canada',
    '2GN': 'Chevrolet Canada',
    '2H': 'Honda',
    '2HH': 'Acura',
    '2HM': 'Hyundai',
    '2HN': 'Acura',
    '2L': 'Lincoln',
    '2M': 'Mercury',
    '2NV': 'Nova Bus',
    '2P3': 'Plymouth',
    '2T': 'Toyota',
    '2T2': 'Lexus Canada',
    '2V4': 'Volkswagen',
    '2W': 'Western Star',
    '3C3': 'Chrysler',
    '3C4': 'Dodge Mexico',
    '3C6': 'Chrysler',
    '3CZ': 'Honda Mexico',
    '3D': 'Dodge',
    '3F': 'Ford',
    '3G': 'General Motors',
    '3GC': 'Chevrolet Mexico',
    '3GN': 'Chevrolet Mexico',
    '3GY': 'Cadillac',
    '3H': 'Honda',
    '3KP': 'Kia',
    '3LN': 'Lincoln',
    '3MZ': 'Mazda Mexico',
    '3N': Nissan(),
    '3P3': 'Plymouth Mexico',
    '3TM': 'Toyota Mexico',
    '3VW': 'Volkswagen',
    '4A': 'Mitsubishi',
    '4F': 'Mazda',
    '4GD': Opel(),
    '4J': 'Mercedes-Benz',
    '4M': 'Mercury',
    '4RK': 'Nova Bus',
    '4S': 'Subaru-Isuzu Automotive',
    '4S6': 'Honda',
    '4T': 'Toyota',
    '4US': 'BMW',
    '4UZ': 'Frt-Thomas Bus',
    '4V': 'Volvo',
    '5F': 'Honda',
    '5FR': 'Acura',
    '5GA': 'Buick',
    '5GN': 'Hummer',
    '5GR': 'Hummer',
    '5J6': 'Honda',
    '5J8': 'Acura',
    '5L': 'Lincoln',
    '5N1': Nissan(),
    '5NM': 'Hyundai',
    '5NP': 'Hyundai',
    '5T': 'Toyota',
    '5U': 'BMW',
    '5X': 'Hyundai/Kia',
    '5YF': 'Toyota',
    '5YJ': 'Tesla',
    '6AB': 'MAN',
    '6F': 'Ford',
    '6F4': Nissan('Nissan Motor Company'),
    '6F5': 'Kenworth',
    '6FP': 'Ford Motor Company',
    '6G': 'General Motors',
    '6G1': 'Chevrolet',
    '6G2': 'Pontiac',
    '6H': 'Holden',
    '6H8': 'General Motors-Holden',
    '6MM': 'Mitsubishi',
    '6T1': 'Toyota',
    '7A3': 'Honda',
    '8A1': Renault(),
    '8AC': 'Mercedes Benz',
    '8AD': 'Peugeot',
    '8AF': 'Ford',
    '8AG': 'General Motors',
    '8AJ': 'Toyota',
    '8AK': 'Suzuki',
    '8AP': 'Fiat',
    '8AT': 'Iveco',
    '8AW': 'Volkswagen',
    '8BC': 'Citroën',
    '8BR': 'Mercedes-Benz Argentina',
    '8C3': 'Honda',
    '8GD': 'Peugeot',
    '8GG': 'Chevrolet',
    '9BD': 'Fiat Automóveis',
    '9BF': 'Ford',
    '9BG': 'General Motors',
    '9BH': 'Hyundai Motor Company / Hyundai',
    '9BM': 'Mercedes Benz',
    '9BR': 'Toyota',
    '9BS': 'Scania',
    '9BV': 'Volvo Trucks',
    '9BW': 'Volkswagen',
    '9C2': 'Honda Motorcycles',
    '9C6': 'Yamaha',
    '9CD': 'Suzuki Motorcycles',
    '9FB': Renault(),
    '9UJ': 'Chery',
    '9UK': 'Lifan',
    '9UW': 'Kia',
    '19': 'Acura',
    '19X': 'Honda',
    '55': 'Mercedes-Benz',
    '58A': 'Lexus',
    '93H': 'Honda',
    '93R': 'Toyota',
    '93U': 'Audi',
    '93V': 'Audi Brazil',
    '93W': 'Fiat Professional',
    '93X': 'Souza Ramos - Mitsubishi / Suzuki',
    '93Y': Renault(),
    '93Z': 'Iveco',
    '94D': Nissan(),
    '95P': 'CAOA / Hyundai',
    '98M': 'BMW',
    '98R': 'Chery',
    '99A': 'Audi',
    '99J': 'JLR Jaguar Land Rover',
    '935': 'Citroën',
    '936': 'Peugeot',
    '953': 'VW Trucks / MAN',
    '988': 'Jeep',
    'AAV': 'Volkswagen',
    'AFA': 'Ford',
    'AHT': 'Toyota',
    'CL9': 'Wallyscar',
    'GA1': Renault(),
    'JA': 'Isuzu',
    'JA3': 'Mitsubishi',
    'JA4': 'Mitsubishi',
    'JC1': 'Fiat Automobiles/Mazda',
    'JF': 'Fuji Heavy Industries',
    'JH': 'Honda',
    'JH4': 'Acura',
    'JK': 'Kawasaki',
    'JM': 'Mazda',
    'JMB': 'Mitsubishi',
    'JN': Nissan(),
    'JS': 'Suzuki',
    'JT': 'Toyota',
    'JTH': 'Lexus',
    'JTJ': 'Lexus',
    'JY': 'Yamaha',
    'KL': 'Daewoo/GM Korea',
    'KM': 'Hyundai',
    'KN': 'Kia',
    'KNM': Renault('Renault Samsung'),
    'KP': 'SsangYong',
    'L5Y': 'Merato Motorcycle Taizhou Zhongneng',
    'L6T': 'Geely',
    'L56': Renault('Renault Samsung'),
    'LBE': 'Beijing Hyundai',
    'LBV': 'BMW Brilliance',
    'LC0': 'BYD Bus',
    'LDC': 'Dongfeng Peugeot-Citroën',
    'LDY': 'Zhongtong Coach',
    'LE4': 'Beijing Benz',
    'LFM': 'FAW Toyota',
    'LFP': 'FAW Car',
    'LFV': 'FAW-Volkswagen',
    'LGB': 'Dongfeng Nissan',
    'LGH': 'Dong Feng (DFM), China',
    'LGJ': 'Dongfeng Fengshen',
    'LGW': 'Great Wall (Havel)',
    'LGX': 'BYD Auto',
    'LH1': 'FAW Haima',
    'LHG': 'Guangzhou Honda',
    'LJ1': 'JAC',
    'LJD': 'Dongfeng Yueda Kia',
    'LKL': 'Suzhou King Long',
    'LLV': 'Lifan',
    'LMG': 'GAC Trumpchi',
    'LPA': 'Changan PSA (DS Automobiles)',
    'LS5': 'Changan Suzuki',
    'LSG': 'SAIC General Motors',
    'LSJ': 'SAIC MG',
    'LSV': 'SAIC Volkswagen',
    'LSY': 'Brilliance Zhonghua',
    'LTV': 'FAW Toyota (Tianjin)',
    'LVG': 'GAC Toyota',
    'LVH': 'Dongfeng Honda',
    'LVR': 'Changan Mazda',
    'LVS': 'Changan Ford',
    'LVV': 'Chery',
    'LWV': 'GAC Fiat',
    'LZE': 'Isuzu Guangzhou',
    'LZG': 'Shaanxi Automobile Group',
    'LZM': 'MAN',
    'LZW': 'SAIC GM Wuling',
    'LZY': 'Yutong',
    'MA1': 'Mahindra',
    'MA3': 'Suzuki',
    'MA7': 'Honda Siel Cars',
    'MAL': 'Hyundai',
    'MC2': 'Volvo Eicher commercial vehicles limited.',
    'MHR': 'Honda',
    'MM0': 'Mazda',
    'MM8': 'Mazda',
    'MMB': 'Mitsubishi',
    'MMM': 'Chevrolet',
    'MMT': 'Mitsubishi',
    'MNB': 'Ford',
    'MNT': Nissan(),
    'MP1': 'Isuzu',
    'MPA': 'Isuzu',
    'MR0': 'Toyota',
    'MRH': 'Honda',
    'MS0': 'KIA Myanmar',
    'NLE': 'Mercedes-Benz Turk Truck',
    'NM0': 'Ford Otosan',
    'NM4': 'Tofas Turk',
    'NMT': 'Toyota',
    'PE1': 'Ford',
    'PE3': 'Mazda',
    'PL1': 'Proton',
    'SAJ': 'Jaguar',
    'SAL': 'Land Rover',
    'SAR': 'Rover',
    'SAT': 'Triumph',
    'SB1': 'Toyota',
    'SCA': 'Rolls Royce',
    'SCB': 'Bentley',
    'SCC': 'Lotus Cars',
    'SCE': 'DeLorean',
    'SCF': 'Aston Martin Lagonda Limited',
    'SDB': 'Peugeot UK',
    'SFD': 'Alexander Dennis',
    'SHH': 'Honda',
    'SHS': 'Honda',
    'SJN': Nissan(),
    'SKF': Opel(),
    'SU9': 'Solaris Bus & Coach',
    'TCC': 'Micro Compact Car AG (SMART 1998-1999)',
    'TDM': 'QUANTYA Swiss Electric Movement',
    'TK9': 'SOR',
    'TM9': 'Škoda trolleybuses',
    'TMA': 'Hyundai',
    'TMB': 'Škoda',
    'TMK': 'Karosa',
    'TMP': 'Škoda trolleybuses',
    'TMT': 'Tatra',
    'TN9': 'Karosa',
    'TRA': 'Ikarus Bus',
    'TRU': 'Audi',
    'TSE': 'Ikarus Egyedi Autobuszgyar',
    'TSM': 'Suzuki',
    'U5Y': 'Kia',
    'UU': 'Dacia',
    'UU1': Renault('Renault Dacia'),
    'VA0': 'ÖAF',
    'VF1': Renault(),
    'VF2': Renault(),
    'VF3': 'Peugeot',
    'VF4': 'Talbot',
    'VF5': 'Iveco Unic SA',
    'VF6': 'Renault Trucks/Volvo',
    'VF7': 'Citroën',
    'VF8': 'Matra/Talbot/Simca',
    'VF9': 'Bugatti',
    'VFE': 'IvecoBus',
    'VLU': 'Scania',
    'VN1': Opel(),
    'VNE': 'Irisbus',
    'VNK': 'Toyota',
    'VS5': Renault(),
    'VS6': 'Ford',
    'VS9': 'Carrocerias Ayats',
    'VSE': 'Suzuki / Santana Motors',
    'VSK': Nissan(),
    'VSS': 'SEAT',
    'VSX': Opel('Opel'),
    'VSY': Renault(),
    'VV9': 'Tauro Sport Auto',
    'VWV': 'Volkswagen',
    'VX1': 'Zastava / Yugo',
    'W0L': Opel('Opel/Vauxhall'),
    'W0S': Opel('Opel Special Vehicles'),
    'W04': 'Buick',
    'W09': 'Ruf Automobile',
    'WA1': 'Audi',
    'WAG': 'Neoplan',
    'WAP': 'Alpina',
    'WAU': 'Audi',
    'WB': 'BMW',
    'WBS': 'BMW M',
    'WCD': 'Mercedes-Benz (Sprinter)',
    'WD3': 'Daimler AG (Sprinter)',
    'WD4': 'Daimler AG (Sprinter)',
    'WDA': 'Daimler AG (Sprinter)',
    'WDB': 'Mercedes-Benz',
    'WDC': 'DaimlerChrysler AG/Daimler AG',
    'WDD': 'DaimlerChrysler AG/Daimler AG',
    'WDP': 'Mercedes-Benz (Sprinter)',
    'WDR': 'Mercedes-Benz (Sprinter)',
    'WDY': 'Mercedes-Benz (Sprinter)',
    'WDZ': 'Mercedes-Benz (Sprinter)',
    'WEB': 'EvoBus',
    'WF0': 'Ford of Europe',
    'WJM': 'Iveco',
    'WJR': 'Irmscher',
    'WKK': 'Karl Kässbohrer Fahrzeugwerke',
    'WMA': 'MAN',
    'WME': 'Smart',
    'WMW': 'Mini',
    'WMX': 'DaimlerChrysler AG/Daimler AG',
    'WP0': 'Porsche car',
    'WP1': 'Porsche SUV',
    'WUA': 'Quattro',
    'WV': 'Volkswagen',
    'WV1': 'Volkswagen Commercial Vehicles',
    'WV2': 'Volkswagen Commercial Vehicles',
    'WV3': 'Volkswagen Trucks',
    'X7L': Renault(),
    'XL9': 'Spyker',
    'XLR': 'DAF Trucks',
    'XMC': 'Mitsubishi (NedCar)',
    'XTA': Lada('AvtoVAZ'),
    'XUF': Opel(),
    'XWF': Opel(),
    'Y6D': Opel(),
    'YH4': 'Fisker',
    'YK1': 'Saab',
    'YS2': 'Scania, Södertälje',
    'YS3': 'Saab',
    'YS4': 'Scania, Katrineholm',
    'YTN': 'Saab NEVS',
    'YV1': 'Volvo Cars',
    'YV2': 'Volvo Trucks',
    'YV3': 'Volvo Buses',
    'YV4': 'Volvo Cars',
    'ZA9': 'Bugatti',
    'ZAM': 'Maserati',
    'ZAP': 'Piaggio/Vespa/Gilera',
    'ZAR': 'Alfa Romeo',
    'ZCF': 'Iveco',
    'ZCG': 'Cagiva SpA',
    'ZD4': 'Aprilia',
    'ZDF': 'Ferrari Dino',
    'ZDM': 'Ducati Motor Holdings SpA',
    'ZFA': 'Fiat Automobiles',
    'ZFC': 'Fiat V.I.',
    'ZFF': 'Ferrari',
    'ZGA': 'IvecoBus',
    'ZHW': 'Lamborghini',
    'ZLA': 'Lancia',
    'ZOM': 'OM',
}
